import { randomInt } from 'node:crypto';
import { config } from '../config.js';
import type { Queryable } from '../db/pool.js';
import { AppError } from '../errors.js';

export type CouponStatus = 'available' | 'redeemed';

export interface CouponView {
  id: string;
  code: string;
  milestone: number;
  percentOff: number;
  status: CouponStatus;
  createdAt: string;
}

export interface CouponListItem extends CouponView {
  redeemedAt: string | null;
  redeemedOrderId: string | null;
}

interface CouponRow {
  id: string;
  code: string;
  milestone: number | string;
  percent_off: number | string;
  status: CouponStatus;
  created_at: Date;
  redeemed_at: Date | null;
}

function toCouponView(row: CouponRow): CouponView {
  return {
    id: row.id,
    code: row.code,
    milestone: Number(row.milestone),
    percentOff: Number(row.percent_off),
    status: row.status,
    createdAt: row.created_at.toISOString(),
  };
}

// A–Z plus 2–9: 34 symbols, so 34^8 ≈ 1.8e12 possible codes.
const CODE_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ23456789';
const CODE_LENGTH = 8;

/** 'SAVE-' + 8 characters from a cryptographically secure source (never Math.random). */
export function generateCouponCode(): string {
  let code = '';
  for (let i = 0; i < CODE_LENGTH; i++) {
    code += CODE_ALPHABET[randomInt(CODE_ALPHABET.length)];
  }
  return `SAVE-${code}`;
}

export interface MilestoneStatus {
  everyNOrders: number;
  percentOff: number;
  ordersPlaced: number;
  couponsGenerated: number;
  nextMilestoneAt: number;
  /** True when POST /admin/coupons would create a coupon right now. */
  eligible: boolean;
}

/**
 * Where the store stands relative to the next coupon milestone. Read-only.
 *
 * Milestones are numbered by how many coupons exist so far, not by the current order
 * count, so milestones missed while nobody generated a coupon still accumulate:
 * with N = 3 and 6 orders placed, two generations produce milestones 3 and 6.
 */
export async function getMilestoneStatus(db: Queryable): Promise<MilestoneStatus> {
  const n = config.COUPON_EVERY_N_ORDERS;
  // COUNT(*) is a bigint, which pg returns as a string.
  const counts = await db.query<{ orders_placed: string; coupons_generated: string }>(
    `SELECT (SELECT COUNT(*) FROM orders)  AS orders_placed,
            (SELECT COUNT(*) FROM coupons) AS coupons_generated`,
  );
  const ordersPlaced = Number(counts.rows[0]!.orders_placed);
  const couponsGenerated = Number(counts.rows[0]!.coupons_generated);
  const nextMilestoneAt = (couponsGenerated + 1) * n;
  return {
    everyNOrders: n,
    percentOff: config.COUPON_PERCENT_OFF,
    ordersPlaced,
    couponsGenerated,
    nextMilestoneAt,
    eligible: ordersPlaced >= nextMilestoneAt,
  };
}

/** Creates the coupon for the next unclaimed milestone (every Nth order). */
export async function generateCoupon(db: Queryable): Promise<CouponView> {
  // a.-c. The next milestone must have been reached.
  const { ordersPlaced, nextMilestoneAt: nextMilestone, eligible } = await getMilestoneStatus(db);
  if (!eligible) {
    throw new AppError(
      409,
      'NO_ELIGIBLE_MILESTONE',
      `No coupon available yet: ${ordersPlaced} orders placed, next coupon at ${nextMilestone}`,
      { ordersPlaced, nextMilestoneAt: nextMilestone },
    );
  }

  // d./e. Insert; the UNIQUE(milestone) constraint decides races.
  //
  // Race: two admin requests can read the same counts and both try to insert the same
  // milestone. The second INSERT blocks on the unique index until the first transaction
  // finishes. If the first committed, ON CONFLICT DO NOTHING makes the second insert
  // nothing, so it gets 0 rows and we report COUPON_ALREADY_GENERATED instead of creating
  // a duplicate. If the first rolled back, the second insert goes through.
  //
  // A clash on `code` (UNIQUE) is not handled here: at 1.8e12 possible codes it is
  // vanishingly unlikely, and it would surface as a 500 rather than a duplicate coupon.
  const { rows } = await db.query<CouponRow>(
    `INSERT INTO coupons (code, milestone, percent_off)
     VALUES ($1, $2, $3)
     ON CONFLICT (milestone) DO NOTHING
     RETURNING *`,
    [generateCouponCode(), nextMilestone, config.COUPON_PERCENT_OFF],
  );
  const created = rows[0];
  if (!created) {
    throw new AppError(
      409,
      'COUPON_ALREADY_GENERATED',
      `The coupon for milestone ${nextMilestone} was just generated by another request`,
      { milestone: nextMilestone },
    );
  }
  return toCouponView(created);
}

/** All coupons, newest first, with the order that redeemed each one (if any). */
export async function listCoupons(db: Queryable): Promise<CouponListItem[]> {
  const { rows } = await db.query<CouponRow & { redeemed_order_id: string | null }>(
    `SELECT c.*, o.id AS redeemed_order_id
       FROM coupons c
       LEFT JOIN orders o ON o.coupon_id = c.id
      ORDER BY c.created_at DESC, c.milestone DESC`,
  );
  return rows.map((row) => ({
    ...toCouponView(row),
    redeemedAt: row.redeemed_at ? row.redeemed_at.toISOString() : null,
    redeemedOrderId: row.redeemed_order_id,
  }));
}
